name: arrival_kc
description: Connecting local businesses with loyal customers.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^0.3.9+1
  flutter_socket_io: ^0.6.0
  location: ^3.0.2
  image_picker: ^0.6.7+7
  flutter_speed_dial: ^1.2.5
  cloudinary_client: ^0.0.9
  video_player: ^0.10.12+2
  loading: ^1.0.2
  flutter_polyline_points: ^0.1.0
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  intl: ^0.16.1
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.7
  uuid: ^2.0.4
  url_launcher: ^5.4.10
  path_provider: ^1.6.11
  flutter_svg: ^0.19.0
  # adobe_xd: ^1.0.0+1 // removed due to incompatibilty with other depends.

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/logo.jpg
    - assets/images/stft.jpg
    - assets/empty.jpg
    - assets/icon/default-profile-pic.png
    - assets/design/blobs/red.svg
    - assets/design/blobs/blue.svg
    - assets/design/blobs/black.svg
    - assets/design/blobs/yellow.svg
    - assets/design/blobs/cream.svg

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/NotoSans/NotoSans-Italic.ttf
          style: italic
          weight: 400
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue/BebasNeue-Regular.ttf
          weight: 400
        - asset: assets/fonts/BebasNeue/BebasNeue-Bold.ttf
          weight: 700
        - asset: assets/fonts/BebasNeue/BebasNeue-Light.ttf
          weight: 300
        - asset: assets/fonts/BebasNeue/BebasNeue-Book.ttf
          weight: 200
        - asset: assets/fonts/BebasNeue/BebasNeue-Thin.ttf
          weight: 100
    - family: HelveticaHeavy
      fonts:
        - asset: assets/fonts/Helvetica/Helvetica-Heavy.ttf
          weight: 400
    - family: UraeNium
      fonts:
        - asset: assets/fonts/urae_nium/urae_nium.ttf
          weight: 400
