name: arrival_kc
description: Connecting local businesses with loyal customers.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_socket_io: ^0.6.0
  flutter_login: ^1.0.14
  photo_view: ^0.10.2
  video_player: ^0.10.0
  chewie: ^0.10.3+1
  media_gallery: ^0.1.4
  exif: ^1.0.3
  transparent_image: ^1.0.0
  permission_handler: ^5.0.1+1
  camera: ^0.5.8+8
  image_picker: ^0.6.7+11
  flutter_speed_dial: ^1.2.5
  cloudinary_client: ^0.0.9
  dio: ^3.0.2
  crypto: ^2.0.6
  pull_to_refresh: ^1.6.1
  drop_cap_text: ^1.0.7
  google_maps_flutter: ^1.0.6
  flutter_polyline_points: ^0.1.0
  cupertino_icons: ^1.0.0
  geolocator: ^5.1.4+2
  intl: ^0.16.1
  share: any
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.7
  uuid: ^2.0.4
  url_launcher: ^5.7.2
  path_provider: ^1.6.11
  flutter_svg: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/arrival/titleasset.png
    - assets/images/slide_menu/city.jpg
    - assets/images/slide_menu/arts.jpg
    - assets/empty.jpg
    - assets/icon/default-profile-pic.png
    - assets/design/blobs/red.svg
    - assets/design/blobs/blue.svg
    - assets/design/blobs/black.svg
    - assets/design/blobs/yellow.svg
    - assets/design/blobs/cream.svg
    - assets/icon/paint/red.png
    - assets/icon/paint/blue.png
    - assets/icon/paint/yellow.png

    - assets/icon/paint/splash/red0.svg
    - assets/icon/paint/splash/blue0.svg
    - assets/icon/paint/splash/yellow0.svg
    - assets/icon/paint/splash/red1.svg
    - assets/icon/paint/splash/blue1.svg
    - assets/icon/paint/splash/yellow1.svg
    - assets/icon/paint/splash/red2.svg
    - assets/icon/paint/splash/blue2.svg
    - assets/icon/paint/splash/yellow2.svg
    - assets/icon/paint/splash/red3.svg
    - assets/icon/paint/splash/blue3.svg
    - assets/icon/paint/splash/yellow3.svg
    - assets/icon/paint/splash/red4.svg
    - assets/icon/paint/splash/blue4.svg
    - assets/icon/paint/splash/yellow4.svg
    - assets/icon/paint/splash/logo.svg
    - assets/icon/paint/splash/logo.png
    # - assets/icon/paint/splash/logo1.svg
    # - assets/icon/paint/splash/logo2.svg
    # - assets/icon/paint/splash/logo3.svg
    # - assets/icon/paint/splash/logo4.svg
    - assets/icon/paint/spray/red0.png
    - assets/icon/paint/spray/blue0.png
    - assets/icon/paint/spray/yellow0.png
    - assets/icon/paint/spray/red1.png
    - assets/icon/paint/spray/blue1.png
    - assets/icon/paint/spray/yellow1.png
    - assets/icon/paint/spray/red2.png
    - assets/icon/paint/spray/blue2.png
    - assets/icon/paint/spray/yellow2.png

    - assets/icon/driving_pin.png
    - assets/icon/destination_map_marker.png
    - assets/loading/Bucket-1s-200px.svg
    - assets/loading/Bucket-1s-200px.gif
    - assets/loading/Spinner-1s-201px.svg
    - assets/loading/Spinner-1s-201px.gif

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/NotoSans/NotoSans-Italic.ttf
          style: italic
          weight: 400
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue/BebasNeue-Regular.ttf
          weight: 400
        - asset: assets/fonts/BebasNeue/BebasNeue-Bold.ttf
          weight: 700
        - asset: assets/fonts/BebasNeue/BebasNeue-Light.ttf
          weight: 300
        - asset: assets/fonts/BebasNeue/BebasNeue-Book.ttf
          weight: 200
        - asset: assets/fonts/BebasNeue/BebasNeue-Thin.ttf
          weight: 100
    - family: HelveticaHeavy
      fonts:
        - asset: assets/fonts/Helvetica/Helvetica-Heavy.ttf
          weight: 400
    - family: UraeNium
      fonts:
        - asset: assets/fonts/urae_nium/urae_nium.ttf
          weight: 400
