name: arrival_kc
description: Connecting local businesses with loyal customers.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^0.3.9+1
  flutter_socket_io: ^0.6.0
  location: ^3.0.2
  flutter_polyline_points: ^0.1.0
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  intl: ^0.16.1
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.7
  uuid: ^2.0.4
  url_launcher: ^5.4.10
  path_provider: ^1.6.11
  adobe_xd: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/logo.jpg
    - assets/images/stft.jpg
    - assets/empty.jpg
    - assets/icon/default-profile-pic.png

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/NotoSans/NotoSans-Italic.ttf
          style: italic
          weight: 400
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue/BebasNeue-Regular.ttf
          weight: 400
        - asset: assets/fonts/BebasNeue/BebasNeue-Bold.ttf
          weight: 700
        - asset: assets/fonts/BebasNeue/BebasNeue-Light.ttf
          weight: 300
        - asset: assets/fonts/BebasNeue/BebasNeue-Book.ttf
          weight: 200
        - asset: assets/fonts/BebasNeue/BebasNeue-Thin.ttf
          weight: 100
    - family: HelveticaHeavy
      fonts:
        - asset: assets/fonts/Helvetica/Helvetica-Heavy.ttf
          weight: 400
    - family: UraeNium
      fonts:
        - asset: assets/fonts/urae_nium/urae_nium.ttf
          weight: 400
